language: go

go:
  - "1.7"
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "tip"

before_install:
  - go get -t -v ./...

env:
  - GO111MODULE=on

script:
  - go test -race -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
